In [1]:
import pickle
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [15]:
!ls "/content/gdrive/MyDrive/Colab Notebooks/nlp udemy"

 ARegular_expression
'chat bots.ipynb'
'keras prac.ipynb'
 LDA.ipynb
'Lematization and stop Words.ipynb'
 moby_dick_four_chapters.txt
'Named Entity Recognition.ipynb'
'NLP Basic.ipynb'
'NLP Tokenize Part 1.ipynb'
'Non negative matrix Factorization.ipynb'
 npr.csv
'Parts of Speech Tagging.ipynb'
 python-regular-expressions-cheat-sheet.pdf
'regular expression practise.ipynb'
'Semantics and word vectors.ipynb'
'Sentence Segmentation.ipynb'
'Sentiment Analysis.ipynb'
 spam.csv
 Stemmer.ipynb
'Text CLassification.ipynb'
'Text Generation with LSTMs with Keras.ipynb'
 train_qa.txt
'Vocabulary and matching.ipynb'


In [8]:
with open("/content/gdrive/MyDrive/Colab Notebooks/nlp udemy/train_qa.txt",'rb') as f:
          train_data=pickle.load(f)

In [16]:
with open("/content/gdrive/MyDrive/Colab Notebooks/nlp udemy/test_qa.txt",'rb') as f:
          test_data=pickle.load(f)

In [17]:
type(train_data)

list

In [18]:
type(test_data)

list

In [19]:
len(train_data)

10000

In [20]:
len(test_data)

1000

In [21]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [23]:
" ".join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [24]:
" ".join(test_data[0][1])

'Is John in the kitchen ?'

In [25]:
all_data=train_data+test_data

In [26]:
len(all_data)

11000

In [27]:
vocab=set()
for story,question,answer in all_data:
  vocab=vocab.union(set(story))
  vocab=vocab.union(set(question))

In [28]:
vocab.add("no")

In [29]:
vocab.add("yes")

In [30]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [31]:
vocab_len=len(vocab)+1

In [32]:
vocab_len

38

In [33]:
all_story_lens=[len(data[0]) for data in all_data]

In [34]:
all_story_lens

[12,
 26,
 39,
 52,
 64,
 12,
 24,
 36,
 49,
 61,
 13,
 25,
 38,
 50,
 63,
 13,
 25,
 37,
 49,
 61,
 24,
 37,
 48,
 71,
 83,
 13,
 25,
 37,
 50,
 62,
 12,
 24,
 35,
 46,
 71,
 12,
 24,
 37,
 50,
 62,
 13,
 25,
 38,
 50,
 62,
 12,
 24,
 36,
 48,
 60,
 13,
 25,
 39,
 50,
 62,
 13,
 26,
 38,
 49,
 60,
 12,
 24,
 36,
 49,
 61,
 13,
 26,
 39,
 51,
 62,
 13,
 25,
 38,
 52,
 65,
 12,
 24,
 37,
 48,
 61,
 13,
 25,
 38,
 51,
 64,
 12,
 25,
 39,
 53,
 65,
 12,
 24,
 36,
 48,
 60,
 12,
 24,
 36,
 49,
 61,
 12,
 25,
 38,
 50,
 61,
 25,
 37,
 49,
 60,
 72,
 13,
 25,
 36,
 48,
 60,
 12,
 24,
 36,
 48,
 60,
 12,
 23,
 36,
 47,
 59,
 12,
 24,
 35,
 48,
 61,
 12,
 23,
 36,
 49,
 62,
 12,
 25,
 37,
 48,
 59,
 12,
 25,
 37,
 49,
 60,
 12,
 24,
 36,
 49,
 61,
 12,
 25,
 37,
 49,
 61,
 12,
 24,
 37,
 49,
 60,
 12,
 25,
 38,
 50,
 61,
 12,
 24,
 36,
 49,
 61,
 12,
 24,
 35,
 48,
 61,
 12,
 25,
 37,
 49,
 62,
 12,
 24,
 38,
 50,
 62,
 12,
 25,
 38,
 50,
 62,
 12,
 24,
 36,
 48,
 60,
 12,
 24,
 36,
 49,
 60,


In [35]:
max_story_len=max(all_story_lens)

In [36]:
max_story_len

156

In [37]:
max_question_len=max(len(data[1]) for data in all_data)

In [38]:
max_question_len

6

In [39]:
from keras.preprocessing.text import Tokenizer

In [40]:
tokenizer=Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [41]:
tokenizer.word_index

{'garden': 1,
 '.': 2,
 'in': 3,
 'office': 4,
 'apple': 5,
 'grabbed': 6,
 'picked': 7,
 'mary': 8,
 'football': 9,
 'the': 10,
 'is': 11,
 'yes': 12,
 'sandra': 13,
 'back': 14,
 'discarded': 15,
 'left': 16,
 'moved': 17,
 'up': 18,
 'journeyed': 19,
 'kitchen': 20,
 'bathroom': 21,
 'put': 22,
 'john': 23,
 'daniel': 24,
 'went': 25,
 'there': 26,
 'milk': 27,
 'hallway': 28,
 'to': 29,
 'travelled': 30,
 'no': 31,
 'down': 32,
 'took': 33,
 'got': 34,
 'dropped': 35,
 'bedroom': 36,
 '?': 37}

In [42]:
train_story_text=[]
train_question_text=[]
train_answers=[]

In [43]:
for story,question,answer in train_data:
  train_story_text.append(story)
  train_question_text.append(question)
  train_answers.append(answer)

In [44]:
train_story_text

[['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.',
  'Sandra',
  'went',
  'to',
  'the',
  'kitchen',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'bathroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to

In [45]:
train_story_seq=tokenizer.texts_to_sequences(train_story_text)

In [47]:
len(train_story_seq)

10000

In [48]:
train_story_seq

[[8, 17, 29, 10, 21, 2, 13, 19, 29, 10, 36, 2],
 [8,
  17,
  29,
  10,
  21,
  2,
  13,
  19,
  29,
  10,
  36,
  2,
  8,
  25,
  14,
  29,
  10,
  36,
  2,
  24,
  25,
  14,
  29,
  10,
  28,
  2],
 [8,
  17,
  29,
  10,
  21,
  2,
  13,
  19,
  29,
  10,
  36,
  2,
  8,
  25,
  14,
  29,
  10,
  36,
  2,
  24,
  25,
  14,
  29,
  10,
  28,
  2,
  13,
  25,
  29,
  10,
  20,
  2,
  24,
  25,
  14,
  29,
  10,
  21,
  2],
 [8,
  17,
  29,
  10,
  21,
  2,
  13,
  19,
  29,
  10,
  36,
  2,
  8,
  25,
  14,
  29,
  10,
  36,
  2,
  24,
  25,
  14,
  29,
  10,
  28,
  2,
  13,
  25,
  29,
  10,
  20,
  2,
  24,
  25,
  14,
  29,
  10,
  21,
  2,
  24,
  7,
  18,
  10,
  9,
  26,
  2,
  24,
  25,
  29,
  10,
  36,
  2],
 [8,
  17,
  29,
  10,
  21,
  2,
  13,
  19,
  29,
  10,
  36,
  2,
  8,
  25,
  14,
  29,
  10,
  36,
  2,
  24,
  25,
  14,
  29,
  10,
  28,
  2,
  13,
  25,
  29,
  10,
  20,
  2,
  24,
  25,
  14,
  29,
  10,
  21,
  2,
  24,
  7,
  18,
  10,
  9,
  26,
  2,
  24,
  

In [83]:
def vectorize_stroies(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_question_len=max_question_len):
  #stories
  X=[]
  #questions
  Xq=[]
  #answer yes or no
  Y=[]

  for story,query,answer in data:
    x=[word_index[word.lower()] for word in story]
    xq=[word_index[word.lower()] for word in query]
    # Pad the sequences to a fixed length
    x = [0] * (max_story_len - len(x)) + x[-max_story_len:]
    xq = [0] * (max_question_len - len(xq)) + xq[-max_question_len:]

    y=np.zeros(len(word_index)+1)
    y[word_index[answer]]=1
    X.append(x)
    Xq.append(xq)
    Y.append(y)
  return (np.array(X), np.array(Xq), np.array(Y))



In [84]:
inputs_train,queries_train,answers_train=vectorize_stroies(train_data)

In [85]:
inputs_test,queries_test,answers_test=vectorize_stroies(test_data)

In [86]:
inputs_test

array([[ 0,  0,  0, ..., 10, 36,  2],
       [ 0,  0,  0, ..., 10,  1,  2],
       [ 0,  0,  0, ..., 10,  1,  2],
       ...,
       [ 0,  0,  0, ..., 10,  5,  2],
       [ 0,  0,  0, ..., 10,  1,  2],
       [ 0,  0,  0, ...,  5, 26,  2]])

In [87]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [88]:
sum(answers_test)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0., 497.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 503.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [89]:
from keras.models import Sequential,Model

In [90]:
from keras.layers import Embedding


In [91]:
from keras.layers import Input,Activation,Dense,Permute,Dropout,add,dot,concatenate,LSTM

In [92]:
input_sequence=Input((max_story_len,))
question=Input((max_question_len,))

In [93]:
vocab_size=len(vocab)+1

In [94]:
input_encoder_m=Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))



In [95]:
input_encoder_c=Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))



In [96]:
question_encoder=Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,output_dim=64,input_length=max_question_len))
question_encoder.add(Dropout(0.3))



In [97]:
input_encoded_m=input_encoder_m(input_sequence)
input_encoded_c=input_encoder_c(input_sequence)
question_encoded=question_encoder(question)

In [98]:
match=dot([input_encoded_m,question_encoded],axes=(2,2))
match=Activation('softmax')(match)

In [99]:
response=add([match,input_encoded_c])
response=Permute((2,1))(response)

In [100]:
from keras.engine.training import concat
answer=concatenate([response,question_encoded])

In [101]:
answer

<KerasTensor: shape=(None, 6, 220) dtype=float32 (created by layer 'concatenate_1')>

In [102]:
answer=LSTM(32)(answer)

In [103]:
answer=Dropout(0.5)(answer)
answer=Dense(vocab_size)(answer)

In [104]:
answer=Activation('softmax')(answer)

In [105]:
model=Model([input_sequence,question],answer)

In [106]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [107]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 156)]        0           []                               
                                                                                                  
 input_4 (InputLayer)           [(None, 6)]          0           []                               
                                                                                                  
 sequential_3 (Sequential)      (None, None, 64)     2432        ['input_3[0][0]']                
                                                                                                  
 sequential_5 (Sequential)      (None, 6, 64)        2432        ['input_4[0][0]']                
                                                                                            

In [108]:
print(inputs_train.shape,queries_train.shape,answers_train.shape)


(10000, 156) (10000, 6) (10000, 38)


In [109]:
history=model.fit([inputs_train,queries_train],answers_train,batch_size=32,epochs=10,validation_data=([inputs_test,queries_test],answers_test))

Epoch 1/10
313/313 [==============================] - 8s 16ms/step - loss: 0.8904 - accuracy: 0.5012 - val_loss: 0.6980 - val_accuracy: 0.5030
Epoch 2/10
313/313 [==============================] - 6s 20ms/step - loss: 0.7075 - accuracy: 0.4989 - val_loss: 0.6938 - val_accuracy: 0.4970
Epoch 3/10
313/313 [==============================] - 5s 14ms/step - loss: 0.6989 - accuracy: 0.4989 - val_loss: 0.6936 - val_accuracy: 0.4970
Epoch 4/10
313/313 [==============================] - 4s 14ms/step - loss: 0.6969 - accuracy: 0.4925 - val_loss: 0.6938 - val_accuracy: 0.4970
Epoch 5/10
313/313 [==============================] - 6s 20ms/step - loss: 0.6957 - accuracy: 0.4961 - val_loss: 0.6932 - val_accuracy: 0.5030
Epoch 6/10
313/313 [==============================] - 5s 15ms/step - loss: 0.6958 - accuracy: 0.4940 - val_loss: 0.6932 - val_accuracy: 0.5030
Epoch 7/10
313/313 [==============================] - 5s 15ms/step - loss: 0.6960 - accuracy: 0.4972 - val_loss: 0.6991 - val_accuracy: 0.4970

In [110]:
model.save('mybrandnewmode.h5')

In [111]:
model.load_weights('mybrandnewmode.h5')

In [112]:
pred_results=model.predict(([inputs_test,queries_test]))

32/32 [==============================] - 1s 3ms/step


In [113]:
pred_results

array([[2.9652296e-07, 2.6369000e-07, 2.5223292e-07, ..., 2.6384316e-07,
        2.3259042e-07, 2.9259303e-07],
       [2.9709415e-07, 2.6333538e-07, 2.5238108e-07, ..., 2.6446489e-07,
        2.3326014e-07, 2.9338659e-07],
       [2.9820927e-07, 2.6523739e-07, 2.5453198e-07, ..., 2.6616658e-07,
        2.3435996e-07, 2.9615168e-07],
       ...,
       [2.9905692e-07, 2.6613594e-07, 2.5497519e-07, ..., 2.6614254e-07,
        2.3455166e-07, 2.9620662e-07],
       [2.9668101e-07, 2.6416112e-07, 2.5224801e-07, ..., 2.6433602e-07,
        2.3291469e-07, 2.9453568e-07],
       [2.9975470e-07, 2.6523992e-07, 2.5343959e-07, ..., 2.6580003e-07,
        2.3494472e-07, 2.9575830e-07]], dtype=float32)

In [114]:
pred_results.shape

(1000, 38)

In [115]:
val_max=np.argmax(pred_results[0])

In [116]:
for key,val in tokenizer.word_index.items():
  if val == val_max:
    k=key

In [117]:
k

'no'

In [118]:
pred_results[0][val_max]

0.5230317