In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X=iris.data

In [7]:
y=iris.target

In [8]:
from keras.utils import to_categorical

In [9]:
y=to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object=MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler()

In [18]:
scaled_X_train=scaler_object.transform(X_train)

In [21]:
scaled_X_test=scaler_object.transform(X_test)

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 2s - loss: 1.0757 - accuracy: 0.3500 - 2s/epoch - 403ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0708 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0670 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0627 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0580 - accuracy: 0.3500 - 14ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0538 - accuracy: 0.3500 - 13ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0498 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0459 - accuracy: 0.3600 - 12ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0418 - accuracy: 0.3600 - 12ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0377 - accuracy: 0.3900 - 12ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0333 - accuracy: 0.3900 - 12ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0293 - accuracy: 0.3900 - 13ms/epoch - 3ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0248 - accuracy: 

In [27]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 5ms/step


array([[1.0707015e-02, 6.0373431e-01, 3.8555861e-01],
       [9.3864906e-01, 2.5016930e-02, 3.6333974e-02],
       [1.9889642e-04, 4.7906917e-02, 9.5189410e-01],
       [1.0462796e-02, 5.5270499e-01, 4.3683216e-01],
       [4.8016747e-03, 3.9157543e-01, 6.0362285e-01],
       [9.1428304e-01, 3.8331714e-02, 4.7385313e-02],
       [4.1677233e-02, 6.4396727e-01, 3.1435558e-01],
       [1.6380121e-03, 1.7922866e-01, 8.1913340e-01],
       [7.2407085e-03, 3.2185096e-01, 6.7090833e-01],
       [1.8109214e-02, 6.5287244e-01, 3.2901829e-01],
       [3.6944551e-03, 3.4438664e-01, 6.5191889e-01],
       [9.0462911e-01, 4.6072900e-02, 4.9298003e-02],
       [9.3964386e-01, 2.4884908e-02, 3.5471339e-02],
       [9.1087824e-01, 4.2713791e-02, 4.6407938e-02],
       [9.6337485e-01, 1.2853876e-02, 2.3771288e-02],
       [8.5950047e-03, 5.4198766e-01, 4.4941729e-01],
       [2.0183483e-03, 2.2211872e-01, 7.7586293e-01],
       [2.2024371e-02, 6.6755831e-01, 3.1041732e-01],
       [1.4800575e-02, 6.492

In [34]:
raw_predictions = model.predict(scaled_X_test)

2/2 [==============================] - 0s 5ms/step


In [39]:
predictions = (raw_predictions > 0.5).astype(int)

In [41]:
print(predictions)

[[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]]
[[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]]


In [42]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [45]:
predictions = np.argmax(raw_predictions, axis=1)

In [46]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [47]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 16]])

In [48]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.80      0.89        15
           2       0.84      1.00      0.91        16

    accuracy                           0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.95      0.94      0.94        50



In [50]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.94

In [51]:
model.save('Abmodel.h5')

In [52]:
from keras.models import load_model

In [53]:
new_model=load_model('Abmodel.h5')