In [45]:
import pandas as pd

In [46]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [47]:
!ls "/content/gdrive/MyDrive/Colab Notebooks/nlp udemy"

 ARegular_expression
 LDA.ipynb
'Lematization and stop Words.ipynb'
'Named Entity Recognition.ipynb'
'NLP Basic.ipynb'
'NLP Tokenize Part 1.ipynb'
 npr.csv
'Parts of Speech Tagging.ipynb'
 python-regular-expressions-cheat-sheet.pdf
'regular expression practise.ipynb'
'Semantics and word vectors.ipynb'
'Sentence Segmentation.ipynb'
'Sentiment Analysis.ipynb'
 spam.csv
 Stemmer.ipynb
'Text CLassification.ipynb'
'Vocabulary and matching.ipynb'


In [48]:
npr=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/nlp udemy/npr.csv")

In [49]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
ck=CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [52]:
dtm=ck.fit_transform(npr['Article'])

In [53]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [54]:
from sklearn.decomposition import LatentDirichletAllocation

In [55]:
lda=LatentDirichletAllocation(n_components=7,random_state=42)

In [56]:
lda.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [57]:
#Grab the vocabulary of words

In [58]:
len(ck.get_feature_names_out())

54777

In [59]:
ck.get_feature_names_out()[5667]

'bhumibol'

In [60]:
import random

In [61]:
random_word_id=random.randint(0,54777)

In [62]:
ck.get_feature_names_out()[random_word_id]

'scoundrels'

In [63]:
#Grab the topicd

In [64]:
len(lda.components_)

7

In [65]:
lda.components_.shape

(7, 54777)

In [66]:
lda.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [67]:
single_topic=lda.components_[0]

In [68]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [69]:
import numpy as np

In [70]:
arr=np.array([10,200,1])

In [71]:
arr.argsort()

array([2, 0, 1])

In [72]:
#Argsort return index position from least - > Gratest
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [73]:
top_ten_words=single_topic.argsort()[-10:]

In [75]:
for i in top_ten_words:
  print(ck.get_feature_names_out()[i])

new
percent
government
company
million
care
people
health
said
says


In [76]:
#grab the highest prob words per topic

In [78]:
for i,t in enumerate(lda.components_):
  print(f"The top  15 words for topic #{i}")
  print([ck.get_feature_names_out()[index] for index in t.argsort()[-15:]])
  print("\n")

The top  15 words for topic #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


The top  15 words for topic #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


The top  15 words for topic #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


The top  15 words for topic #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


The top  15 words for topic #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


The top  15 words for topic #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 't

In [79]:
topic_results=lda.transform(dtm)

In [80]:
topic_results

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

Non negative matrix Factorization.ipynb

In [81]:
npr=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/nlp udemy/npr.csv")

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [83]:
t=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [84]:
dtm=t.fit_transform(npr['Article'])

In [85]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [87]:
from sklearn.decomposition import NMF

In [88]:
nmf_model=NMF(n_components=7,random_state=42)

In [89]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

In [90]:
t.get_feature_names_out()[2300]

'albala'

In [91]:
for i,t in enumerate(nmf_model.components_):
  print(f"The top  15 words for topic #{i}")
  print([ck.get_feature_names_out()[index] for index in t.argsort()[-15:]])
  print("\n")

The top  15 words for topic #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


The top  15 words for topic #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


The top  15 words for topic #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


The top  15 words for topic #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


The top  15 words for topic #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


The top  15 words for topic #5
['love', 've', 'don

In [92]:
topic_results=nmf_model.transform(dtm)

In [93]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [94]:
npr['Topic']=topic_results.argmax(axis=1)

In [95]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6