In [1]:
from google.colab import drive

In [2]:
import tensorflow as tf
import seaborn as sns
import pandas as pd

In [9]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [10]:
!ls

gdrive	sample_data


In [17]:
!ls "gdrive/MyDrive/Colab Notebooks/Youtube Practise/Deep Learning for Computer Vision with Python and TensorFlow"

'Car Price Prediction.ipynb'   car_train.csv   Tensors.ipynb


In [18]:
data=pd.read_csv("gdrive/MyDrive/Colab Notebooks/Youtube Practise/Deep Learning for Computer Vision with Python and TensorFlow/car_train.csv")

In [19]:
data.head()

v.id  on road old  on road now  years      km  rating  condition  economy  \
0     1       535651       798186      3   78945       1          2       14   
1     2       591911       861056      6  117220       5          9        9   
2     3       686990       770762      2  132538       2          8       15   
3     4       573999       722381      4  101065       4          3       11   
4     5       691388       811335      6   61559       3          9       12   

   top speed  hp  torque  current price  
0        177  73     123       351318.0  
1        148  74      95       285001.5  
2        181  53      97       215386.0  
3        197  54     116       244295.5  
4        160  53     105       531114.5

In [21]:
data.shape

(1000, 12)

In [24]:
sns.pairplot(data,diag_kind='kde')

Output hidden; open in https://colab.research.google.com to view.

In [26]:
tensor_data=tf.constant(data)
tensor_data=tf.cast(tensor_data,tf.float32)
print(tensor_data)

tf.Tensor(
[[1.000000e+00 5.356510e+05 7.981860e+05 ... 7.300000e+01 1.230000e+02
  3.513180e+05]
 [2.000000e+00 5.919110e+05 8.610560e+05 ... 7.400000e+01 9.500000e+01
  2.850015e+05]
 [3.000000e+00 6.869900e+05 7.707620e+05 ... 5.300000e+01 9.700000e+01
  2.153860e+05]
 ...
 [9.980000e+02 6.463440e+05 8.427330e+05 ... 1.130000e+02 8.900000e+01
  4.058710e+05]
 [9.990000e+02 5.355590e+05 7.324390e+05 ... 1.120000e+02 1.280000e+02
  7.439800e+04]
 [1.000000e+03 5.901050e+05 7.797430e+05 ... 9.900000e+01 9.600000e+01
  4.149385e+05]], shape=(1000, 12), dtype=float32)


In [27]:
tensor_data=tf.random.shuffle(tensor_data)
print(tensor_data[:5])

tf.Tensor(
[[8.260000e+02 5.061150e+05 7.850620e+05 6.000000e+00 1.471290e+05
  2.000000e+00 1.000000e+00 1.500000e+01 1.670000e+02 7.700000e+01
  7.000000e+01 5.347050e+04]
 [8.170000e+02 6.694060e+05 8.461870e+05 2.000000e+00 9.027300e+04
  5.000000e+00 2.000000e+00 1.200000e+01 1.860000e+02 5.000000e+01
  1.130000e+02 3.985135e+05]
 [5.550000e+02 6.027370e+05 7.172370e+05 2.000000e+00 1.432420e+05
  3.000000e+00 8.000000e+00 9.000000e+00 1.600000e+02 1.060000e+02
  1.210000e+02 1.037425e+05]
 [7.520000e+02 5.061210e+05 7.637060e+05 2.000000e+00 5.855700e+04
  4.000000e+00 2.000000e+00 1.500000e+01 1.960000e+02 9.700000e+01
  8.700000e+01 4.015000e+05]
 [1.880000e+02 6.327940e+05 7.344800e+05 7.000000e+00 1.201380e+05
  3.000000e+00 9.000000e+00 1.000000e+01 1.550000e+02 5.200000e+01
  1.050000e+02 2.245335e+05]], shape=(5, 12), dtype=float32)


In [28]:
X=tensor_data[:,3:-1]
print(X[:5])

tf.Tensor(
[[6.00000e+00 1.47129e+05 2.00000e+00 1.00000e+00 1.50000e+01 1.67000e+02
  7.70000e+01 7.00000e+01]
 [2.00000e+00 9.02730e+04 5.00000e+00 2.00000e+00 1.20000e+01 1.86000e+02
  5.00000e+01 1.13000e+02]
 [2.00000e+00 1.43242e+05 3.00000e+00 8.00000e+00 9.00000e+00 1.60000e+02
  1.06000e+02 1.21000e+02]
 [2.00000e+00 5.85570e+04 4.00000e+00 2.00000e+00 1.50000e+01 1.96000e+02
  9.70000e+01 8.70000e+01]
 [7.00000e+00 1.20138e+05 3.00000e+00 9.00000e+00 1.00000e+01 1.55000e+02
  5.20000e+01 1.05000e+02]], shape=(5, 8), dtype=float32)


In [39]:
y=tensor_data[:,-1]
print(y[:5])

tf.Tensor([ 53470.5 398513.5 103742.5 401500.  224533.5], shape=(5,), dtype=float32)


In [41]:
y=tf.expand_dims(y,axis=-1)
print(y[:5])

tf.Tensor(
[[[ 53470.5]]

 [[398513.5]]

 [[103742.5]]

 [[401500. ]]

 [[224533.5]]], shape=(5, 1, 1), dtype=float32)


In [32]:
from tensorflow.keras.layers import Normalization

In [44]:
normalizer=Normalization()
x_normalized=tf.constant([[3,4,5,6,7],
                          [4,5,6,7,8]])


In [45]:
print(x_normalized)

tf.Tensor(
[[3 4 5 6 7]
 [4 5 6 7 8]], shape=(2, 5), dtype=int32)


In [46]:
normalizer(x_normalized)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]], dtype=float32)>

In [54]:

normalizer=Normalization()
x_normalized=tf.constant([[3,4,5,6,7],
                          [4,5,6,7,8]])
normalizer.adapt(x_normalized)
normalizer(x_normalized)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>

In [55]:
#Normalizing
normalizer=Normalization()
normalizer.adapt(X)
normalizer(X)[:5]

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 0.8374949 ,  1.6081396 , -0.7046622 , -1.6266173 ,  1.5138373 ,
         0.00554988, -0.3679775 , -1.5879277 ],
       [-1.4904963 , -0.34326845,  1.4350005 , -1.2723888 ,  0.16820414,
         0.99109185, -1.6846216 ,  0.45500377],
       [-1.4904963 ,  1.4747303 ,  0.00855871,  0.8529823 , -1.177429  ,
        -0.35754454,  1.0461957 ,  0.835084  ],
       [-1.4904963 , -1.431823  ,  0.72177964, -1.2723888 ,  1.5138373 ,
         1.5097982 ,  0.60731435, -0.7802571 ],
       [ 1.4194927 ,  0.6817562 ,  0.00855871,  1.2072108 , -0.72888464,
        -0.6168977 , -1.5870924 ,  0.07492349]], dtype=float32)>

In [57]:
#4hr 57 min