In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.2.1+cu121'

In [4]:
arr=np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [8]:
x=torch.from_numpy(arr)

In [9]:
x

tensor([1, 2, 3, 4, 5])

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [11]:
x.dtype

torch.int64

In [12]:
arr2d=np.arange(0.0,12.0)

In [13]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
arr2d=arr2d.reshape(4,3)

In [16]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [18]:
arr2=torch.from_numpy(arr2d)

In [19]:
arr2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

Tensor basics part 2

In [20]:
new_arr=np.array([1,2,3])

In [21]:
new_arr.dtype

dtype('int64')

In [22]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [23]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])

In [24]:
torch.empty(4,2)

tensor([[3.7171e+32, 4.5214e-41],
        [4.9707e-25, 3.2499e-41],
        [4.4842e-44, 0.0000e+00],
        [8.9683e-44, 0.0000e+00]])

In [25]:
torch.zeros(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [27]:
torch.ones(1,3)

tensor([[1., 1., 1.]])

In [28]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [29]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [30]:
torch.rand(10)

tensor([0.8117, 0.4709, 0.0499, 0.0208, 0.9870, 0.2663, 0.3312, 0.2641, 0.8302,
        0.5128])

Tensor operations

In [31]:
torch.arange(6).reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [32]:
torch.arange(6).view((2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])