# Aritificial Neural Network

### 1) Data Preprocessing

In [1]:
pip install numpy

     --------------------------------------- 12.9/12.9 MB 23.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\anubh\anaconda3\AI\AI-Practise-dump\Deep Learning A-Z udemy\Part 1 - Artificial Neural Networks (ANN)\tf_env\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
pip install pandas

     --------------------------------------- 11.3/11.3 MB 28.5 MB/s eta 0:00:00
     ------------------------------------- 509.2/509.2 KB 31.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\anubh\anaconda3\AI\AI-Practise-dump\Deep Learning A-Z udemy\Part 1 - Artificial Neural Networks (ANN)\tf_env\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
pip install -U matplotlib

     ---------------------------------------- 8.1/8.1 MB 27.3 MB/s eta 0:00:00
     ---------------------------------------- 221.2/221.2 KB ? eta 0:00:00
     ---------------------------------------- 1.6/1.6 MB 24.8 MB/s eta 0:00:00
     ---------------------------------------- 121.8/121.8 KB ? eta 0:00:00
     ---------------------------------------- 7.0/7.0 MB 18.0 MB/s eta 0:00:00
     ---------------------------------------- 73.7/73.7 KB ? eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\anubh\anaconda3\AI\AI-Practise-dump\Deep Learning A-Z udemy\Part 1 - Artificial Neural Networks (ANN)\tf_env\Scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Reading the csv file

In [5]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
 X=data.iloc[:,3:-1].values #Start from colum index 3 till the second last column (Except the Last column)

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
y=data.iloc[:,-1].values #Contains the Last column only

In [9]:
print(y)

[1 0 1 ... 1 1 0]


In [10]:
print(X.shape,y.shape)

(10000, 10) (10000,)


### 2) Encoding Categorical Data

In [11]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [13]:
pip install scikit-learn

     ---------------------------------------- 8.9/8.9 MB 22.7 MB/s eta 0:00:00
     ------------------------------------- 309.1/309.1 KB 19.9 MB/s eta 0:00:00
     --------------------------------------- 41.3/41.3 MB 18.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\anubh\anaconda3\AI\AI-Practise-dump\Deep Learning A-Z udemy\Part 1 - Artificial Neural Networks (ANN)\tf_env\Scripts\python.exe -m pip install --upgrade pip' command.


In [14]:
from sklearn.preprocessing import LabelEncoder


In [15]:
le=LabelEncoder()

#### Label Encoding Gender

In [16]:
X[:,2]=le.fit_transform(X[:,2])

In [17]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One hot encoding the Geography Column

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [19]:
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')

In [20]:
X=np.array(ct.fit_transform(X))

In [21]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Splitting the data into Training and Testing 

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

#### Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [25]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## 3) Building ANN

In [26]:
pip install --upgrade pip

     ---------------------------------------- 1.8/1.8 MB 11.3 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Note: you may need to restart the kernel to use updated packages.


In [27]:
pip install tensorflow

  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ---------------------------------------- 0.0/331.7 MB ? eta -:--:--
    --------------------------------------- 5.0/331.7 MB 25.2 MB/s eta 0:00:13
   - -------------------------------------- 10.5/331.7 MB 26.2 MB/s eta 0:00:13
   - -------------------------------------- 13.1/331.7 MB 20.6 MB/s eta 0:00:16
   -- ------------------------------------- 19.1/331.7 MB 22.8 MB/s eta 0:00:14
   --- ------------------------------------ 25.4/331.7 MB 24.0 MB/s eta 0:00:13
   --- --------------------------------

In [29]:
import tensorflow as tf

### Initializing the ANN

In [30]:
ann=tf.keras.models.Sequential()

### Adding the Input Layer and the first hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [34]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Training the ANN

In [35]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training Set

In [36]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7354 - loss: 0.5439
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4412
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7997 - loss: 0.4304
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8059 - loss: 0.4267
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8112 - loss: 0.4240
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8167 - loss: 0.4218
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8211 - loss: 0.4185
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8206 - loss: 0.4145
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8240 - loss: 0.4106
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8253 - loss: 0.4055
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8232 - loss: 0.3998
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## 4) Making the Predictions and Evaluating the Model

In [38]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[0.0322619]], dtype=float32)

### Predicting the Test Set Result

In [39]:
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1504   91]
 [ 189  216]]


0.86