##Intoduction to Tensor

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
#Create Tensor with tf.constant
scalar=tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [3]:
#check number of dimensions of a tensor
scalar.ndim

0

In [4]:
#create a constant
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimension of a vector
vector.ndim

1

In [6]:
#create a matrix
matrix=tf.constant([[2,3],[3,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 2]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#dtype
another_matrix=tf.constant([
                            [3.,2.],
                            [1.,4.],
                            [8.,5.]
                            ],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 2.],
       [1., 4.],
       [8., 5.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:

tensor=tf.constant([[
                     [1,2,3],
                     [4,5,4]],
                     [[5,4,6],
                      [9,2,3]],
                     [[9,0,8],
                      [1,2,3]]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 4]],

       [[5, 4, 6],
        [9, 2, 3]],

       [[9, 0, 8],
        [1, 2, 3]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
#what we have created so far
'''
Scalar-A single number
Vector-A number with direction(eg wind)
Matrix-2 d array
tensor-an n dimensional array
'''

'\nScalar-A single number\nVector-A number with direction(eg wind)\nMatrix-2 d array\ntensor-an n dimensional array\n'

###Creating tensors with `tf.Variable`

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
#difference between constant and Variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,9])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  9], dtype=int32)>)

In [15]:
#changing the changable_tensor
changable_tensor[0].assign(11)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

##Creating a random Tensor

In [16]:
#Creating two random but same tensor
random_1=tf.random.Generator.from_seed(12)
print(random_1.normal(shape=[2,3]))

random_2=tf.random.get_global_generator()
print(random_2.normal(shape=[1,2]))

tf.Tensor(
[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]], shape=(2, 3), dtype=float32)
tf.Tensor([[-0.2021207  0.9039975]], shape=(1, 2), dtype=float32)


In [17]:
#shuffle the order of elements in tensor
not_shuffle=tf.constant([[1,2],[4,5],[0,9]])
tf.random.shuffle(not_shuffle,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 9],
       [4, 5],
       [1, 2]], dtype=int32)>

In [18]:
#random seed
tf.random.set_seed(12)
print(tf.random.uniform([1,1,2],seed=1))



tf.Tensor([[[0.77498245 0.8707615 ]]], shape=(1, 1, 2), dtype=float32)


In [19]:
print(tf.random.set_seed(2))
print(tf.random.uniform([1,1,2],seed=1))

None
tf.Tensor([[[0.23841548 0.37620628]]], shape=(1, 1, 2), dtype=float32)


In [20]:
#if want our tensor to be in same order
#use 1)global level tensor and 2) operational level tensor as mentioned above

##Other ways of creating tensor

In [21]:
tf.ones([10,5],dtype=tf.int32)

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [22]:
import numpy as np
numpy_a=np.arange(1,23,2)
numpy_a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [23]:
A=tf.constant(numpy_a)
A

<tf.Tensor: shape=(11,), dtype=int64, numpy=array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])>

##Getting information from tensors

##Things to be aware of while dealing with tensors
##Shape
##Rank
##axis or dimensions
##size

In [24]:
rank_4_tensor=tf.zeros(shape=[3,2,1,4])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 1, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.]],

        [[0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([3, 2, 1, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [26]:
print("Datatype of tensor",rank_4_tensor.dtype)
print("Number of dimensions",rank_4_tensor.ndim)
print("Shape of Tensor:",rank_4_tensor.shape)
print("Elements along the 0th axis",rank_4_tensor.shape[0])
print("Elements along the last axis",rank_4_tensor.shape[-1])
print("Total number of elements",tf.size(rank_4_tensor))

Datatype of tensor <dtype: 'float32'>
Number of dimensions 4
Shape of Tensor: (3, 2, 1, 4)
Elements along the 0th axis 3
Elements along the last axis 4
Total number of elements tf.Tensor(24, shape=(), dtype=int32)


In [27]:
rank=tf.Variable([[10,2,5,6],[10,2,4,5]])
rank

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[10,  2,  5,  6],
       [10,  2,  4,  5]], dtype=int32)>

In [28]:
rank[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 5], dtype=int32)>

In [29]:
#adding extra dimensions
ra=rank[...,tf.newaxis]
ra

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[10],
        [ 2],
        [ 5],
        [ 6]],

       [[10],
        [ 2],
        [ 4],
        [ 5]]], dtype=int32)>

In [30]:
#alternative
tf.expand_dims(ra,axis=-1)

<tf.Tensor: shape=(2, 4, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 2]],

        [[ 5]],

        [[ 6]]],


       [[[10]],

        [[ 2]],

        [[ 4]],

        [[ 5]]]], dtype=int32)>

In [31]:
tf.expand_dims(ra,axis=1)

<tf.Tensor: shape=(2, 1, 4, 1), dtype=int32, numpy=
array([[[[10],
         [ 2],
         [ 5],
         [ 6]]],


       [[[10],
         [ 2],
         [ 4],
         [ 5]]]], dtype=int32)>

##Manipulating tensors

In [32]:
#basic operations
tensor=tf.constant([[10,5],[9,9]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [19, 19]], dtype=int32)>

In [33]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 90,  90]], dtype=int32)>

In [34]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -5],
       [-1, -1]], dtype=int32)>

In [35]:
tensor * 9

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 45],
       [81, 81]], dtype=int32)>

In [36]:
# +,-,*,/ are elements wise operator
#matrix multiplication with tenserflo
tf.matmul(tensor,tensor)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[145,  95],
       [171, 126]], dtype=int32)>

In [37]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[1,2],[9,8],[0,9]])
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 19,  45],
       [ 49, 102]], dtype=int32)>

In [38]:
#matrix mult with python operator
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 19,  45],
       [ 49, 102]], dtype=int32)>

In [39]:
tf.transpose(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [40]:
tf.reshape(a,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

**The dot product**

In [41]:
#tf.matmul
#tf.tensordot

In [42]:
a,b

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [9, 8],
        [0, 9]], dtype=int32)>)

In [46]:
tf.tensordot(a,b,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 19,  45],
       [ 49, 102]], dtype=int32)>

In [47]:
A=tf.constant([1.4,4.5])
A.dtype

tf.float32

In [48]:
B=tf.constant([4,5])
B.dtype

tf.int32

In [49]:
C=tf.cast(B,dtype=tf.int16)
C

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([4, 5], dtype=int16)>

##Aggregating Tensors

In [51]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [52]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

##Following forms of aggregation
**Get the Minimum**
**Get the maximum**
**Get the mean of a tensor**
**Get the sum of a tensor**

In [59]:
X=tf.constant([2,66,3,22])
Y=tf.constant([0,2,3,4])
tf.math.minimum(X,Y)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 2, 3, 4], dtype=int32)>

In [60]:
tf.math.maximum(X,Y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2, 66,  3, 22], dtype=int32)>

In [62]:
x=tf.constant([[2,4],[0,8]])
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [63]:
tf.reduce_sum(x).numpy()

14

In [65]:
tf.reduce_min(x).numpy()

0

In [66]:
tf.reduce_max(x).numpy()

8

In [67]:
import tensorflow_probability as tfp
tfp.stats.variance(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

##Find the positional maxima and minimum

In [68]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

NameError: ignored

In [70]:
tf.argmax(F).numpy()

In [71]:
tf.argmin(F).numpy()

In [74]:
F[tf.argmax(F)] == tf.reduce_max(F)

###Sqezing a tensor(remove all single dimension)

In [78]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

In [79]:
G.ndim

In [80]:
G.shape

In [81]:
G_squeeze=tf.squeeze(G)
G_squeeze

###One hot - encoding

In [82]:
l=[0,1,2,3]
tf.one_hot(l,depth=4)

##Sqauring,log,square root,

In [83]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [84]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [87]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [88]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##Tensors and Numpy

In [89]:
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [90]:
np.array(J)

array([ 3.,  7., 10.])

In [93]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)