In [3]:
import numpy as np

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.random.rand(4)

array([0.90281121, 0.50700855, 0.68468688, 0.4064606 ])

In [6]:
np.random.seed(100)

In [8]:
np.random.rand(4)

array([0.00471886, 0.12156912, 0.67074908, 0.82585276])

In [9]:
np.random.rand(5,5,4)

array([[[0.13670659, 0.57509333, 0.89132195, 0.20920212],
        [0.18532822, 0.10837689, 0.21969749, 0.97862378],
        [0.81168315, 0.17194101, 0.81622475, 0.27407375],
        [0.43170418, 0.94002982, 0.81764938, 0.33611195],
        [0.17541045, 0.37283205, 0.00568851, 0.25242635]],

       [[0.79566251, 0.01525497, 0.59884338, 0.60380454],
        [0.10514769, 0.38194344, 0.03647606, 0.89041156],
        [0.98092086, 0.05994199, 0.89054594, 0.5769015 ],
        [0.74247969, 0.63018394, 0.58184219, 0.02043913],
        [0.21002658, 0.54468488, 0.76911517, 0.25069523]],

       [[0.28589569, 0.85239509, 0.97500649, 0.88485329],
        [0.35950784, 0.59885895, 0.35479561, 0.34019022],
        [0.17808099, 0.23769421, 0.04486228, 0.50543143],
        [0.37625245, 0.5928054 , 0.62994188, 0.14260031],
        [0.9338413 , 0.94637988, 0.60229666, 0.38776628]],

       [[0.363188  , 0.20434528, 0.27676506, 0.24653588],
        [0.173608  , 0.96660969, 0.9570126 , 0.59797368],
        

In [10]:
np.random.rand(5,5,4).shape

(5, 5, 4)

In [11]:
np.random.randn(7)

array([-0.00889866, -0.54319801,  0.75306219, -1.6094389 ,  1.94326226,
       -1.44743611,  0.13024846])