In [1]:
import numpy as np

In [2]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
a.shape


(20,)

In [4]:
a.ndim

1

In [5]:
a.dtype

dtype('int32')

In [13]:
b=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 5)

In [17]:
c=np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
d=np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [26]:
#number of elements should be equal to rows and columns
arr=np.arange(20).reshape(2,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [27]:
a1=np.array([[1,2],[4,3]])
b1=np.array([[4,2],[6,5]])
a1@b1
#matrix productt

array([[16, 12],
       [34, 23]])

In [28]:
a1.dot(b1)
#matrix product

array([[16, 12],
       [34, 23]])

In [29]:
a1*b1
#element wise product

array([[ 4,  4],
       [24, 15]])

In [31]:
a1.sum()

10

In [32]:
b1.sum()

17

In [33]:
a1.min()

1

In [34]:
b1.min()

2

In [35]:
a1


array([[1, 2],
       [4, 3]])

In [52]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a2.ndim

2

In [54]:
a2.shape

(3, 3)

In [56]:
a2[1:,1:]

array([[5, 6],
       [8, 9]])

In [59]:
a1

array([[1, 2],
       [4, 3]])

In [60]:
b1

array([[4, 2],
       [6, 5]])

In [61]:
np.vstack((a1,b1))

array([[1, 2],
       [4, 3],
       [4, 2],
       [6, 5]])

In [62]:
np.hstack((a1,b1))

array([[1, 2, 4, 2],
       [4, 3, 6, 5]])

In [65]:
np.random.rand(1,5)

array([[0.91413013, 0.51965704, 0.78115659, 0.54000491, 0.43564293]])

In [73]:
np.random.randint(1,5)

3

In [72]:
np.random.randint(1,5,3)

array([4, 3, 2])

In [79]:
a3=np.array([[[1, 2, 4, 2],
       [4, 3, 6, 5],
            [1,2,3,4]]])
a3

array([[[1, 2, 4, 2],
        [4, 3, 6, 5],
        [1, 2, 3, 4]]])

In [80]:
a3.ndim

3

In [81]:
a3.shape

(1, 3, 4)

In [90]:
a3[0,1]

array([4, 3, 6, 5])

### 

In [92]:
a3.argmax()

6

In [93]:
a3

array([[[1, 2, 4, 2],
        [4, 3, 6, 5],
        [1, 2, 3, 4]]])

In [94]:
a3.argmin()

0

In [95]:
a3.dtype

dtype('int32')

In [96]:
np.random.randn(7)

array([ 0.84271815, -0.37989073,  0.38549684, -0.40577467, -0.50440311,
       -1.02502047,  0.2610592 ])