In [2]:
import numpy as np

In [5]:
a=np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
for i in range(len(a)):
    a[i]=i
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [9]:
a[[1,4,5,6]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [10]:
a[[1,4,5,6],2:5]

array([[1., 1., 1.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [13]:
import random

In [17]:
arr=np.random.randint(1,100,25)
arr

array([40, 80, 17, 88,  7, 14, 23, 56, 87, 54, 11, 99, 15, 38, 60, 80, 17,
       73, 47, 13, 44, 33, 11, 66, 71])

In [20]:
x=arr >20
y=arr<20

In [21]:
arr[x]

array([40, 80, 88, 23, 56, 87, 54, 99, 38, 60, 80, 73, 47, 44, 33, 66, 71])

In [22]:
arr[y]

array([17,  7, 14, 11, 15, 17, 13, 11])

In [23]:
z=arr[(arr>20)&(arr<50)]
z

array([40, 23, 38, 47, 44, 33])

In [24]:
x1=np.random.randint(1,50,10)
x2=np.random.randint(1,50,10)

In [25]:
y=10*x1+20*x2
y

array([1030, 1130, 1110, 1120,  560,  840,  460,  950,  570, 1140])

In [26]:
arr


array([40, 80, 17, 88,  7, 14, 23, 56, 87, 54, 11, 99, 15, 38, 60, 80, 17,
       73, 47, 13, 44, 33, 11, 66, 71])

In [27]:
np.exp(arr)

array([2.35385267e+17, 5.54062238e+34, 2.41549528e+07, 1.65163625e+38,
       1.09663316e+03, 1.20260428e+06, 9.74480345e+09, 2.09165950e+24,
       6.07603023e+37, 2.83075330e+23, 5.98741417e+04, 9.88903032e+42,
       3.26901737e+06, 3.18559318e+16, 1.14200739e+26, 5.54062238e+34,
       2.41549528e+07, 5.05239363e+31, 2.58131289e+20, 4.42413392e+05,
       1.28516001e+19, 2.14643580e+14, 5.98741417e+04, 4.60718663e+28,
       6.83767123e+30])

In [28]:
np.log(arr)

array([3.68887945, 4.38202663, 2.83321334, 4.47733681, 1.94591015,
       2.63905733, 3.13549422, 4.02535169, 4.46590812, 3.98898405,
       2.39789527, 4.59511985, 2.7080502 , 3.63758616, 4.09434456,
       4.38202663, 2.83321334, 4.29045944, 3.8501476 , 2.56494936,
       3.78418963, 3.49650756, 2.39789527, 4.18965474, 4.26267988])

In [30]:
def square(x):
    return x*x

In [31]:
square(arr)

array([1600, 6400,  289, 7744,   49,  196,  529, 3136, 7569, 2916,  121,
       9801,  225, 1444, 3600, 6400,  289, 5329, 2209,  169, 1936, 1089,
        121, 4356, 5041])